'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.1
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o vuelva a generar su proyecto de VS.
    '''<summary>
    '''  Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Lucla
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("LuclaApp.Lucla", GetType(Lucla).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Authentication ....
        '''</summary>
        Friend Shared ReadOnly Property Authentication() As String
            Get
                Return ResourceManager.GetString("Authentication", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Update.
        '''</summary>
        Friend Shared ReadOnly Property btnUpdate() As String
            Get
                Return ResourceManager.GetString("btnUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Check argument.
        '''</summary>
        Friend Shared ReadOnly Property CheckArgument() As String
            Get
                Return ResourceManager.GetString("CheckArgument", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Check validity.
        '''</summary>
        Friend Shared ReadOnly Property CheckValidity() As String
            Get
                Return ResourceManager.GetString("CheckValidity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Check Version.
        '''</summary>
        Friend Shared ReadOnly Property ckCheckVersion() As String
            Get
                Return ResourceManager.GetString("ckCheckVersion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error.
        '''</summary>
        Friend Shared ReadOnly Property ErrorTitle() As String
            Get
                Return ResourceManager.GetString("ErrorTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Failed to connect server, please re-update!.
        '''</summary>
        Friend Shared ReadOnly Property FailedtoLinkServer() As String
            Get
                Return ResourceManager.GetString("FailedtoLinkServer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Get data ....
        '''</summary>
        Friend Shared ReadOnly Property GetData() As String
            Get
                Return ResourceManager.GetString("GetData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Get picture.
        '''</summary>
        Friend Shared ReadOnly Property GetModelPic() As String
            Get
                Return ResourceManager.GetString("GetModelPic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Server.
        '''</summary>
        Friend Shared ReadOnly Property lblServer() As String
            Get
                Return ResourceManager.GetString("lblServer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Connecting to server.
        '''</summary>
        Friend Shared ReadOnly Property LinkServer() As String
            Get
                Return ResourceManager.GetString("LinkServer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a This model is lock!.
        '''</summary>
        Friend Shared ReadOnly Property ModelIsLock() As String
            Get
                Return ResourceManager.GetString("ModelIsLock", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a This model is null!.
        '''</summary>
        Friend Shared ReadOnly Property ModelIsNull() As String
            Get
                Return ResourceManager.GetString("ModelIsNull", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Username and password must be entered.
        '''</summary>
        Friend Shared ReadOnly Property MSG_IdAndPasswordCanNotEmpty() As String
            Get
                Return ResourceManager.GetString("MSG_IdAndPasswordCanNotEmpty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Network congestion, please wait ....
        '''</summary>
        Friend Shared ReadOnly Property NetworkCongestion() As String
            Get
                Return ResourceManager.GetString("NetworkCongestion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a No argument!.
        '''</summary>
        Friend Shared ReadOnly Property NoArgument() As String
            Get
                Return ResourceManager.GetString("NoArgument", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ping server ....
        '''</summary>
        Friend Shared ReadOnly Property PingServer() As String
            Get
                Return ResourceManager.GetString("PingServer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Gpscamera.Org Update.
        '''</summary>
        Friend Shared ReadOnly Property TitleName() As String
            Get
                Return ResourceManager.GetString("TitleName", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
