'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.1
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o vuelva a generar su proyecto de VS.
    '''<summary>
    '''  Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class GPSCamera
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("GPSCamera.GPSCamera", GetType(GPSCamera).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Download area code failure, please re-update!.
        '''</summary>
        Friend Shared ReadOnly Property AreaCodeFailure() As String
            Get
                Return ResourceManager.GetString("AreaCodeFailure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Autentication ....
        '''</summary>
        Friend Shared ReadOnly Property Authentication() As String
            Get
                Return ResourceManager.GetString("Authentication", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Authentication failed, Please re-verify!.
        '''</summary>
        Friend Shared ReadOnly Property AuthenticationFailed() As String
            Get
                Return ResourceManager.GetString("AuthenticationFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Failed to download authorization code, network congestion detected!.
        '''</summary>
        Friend Shared ReadOnly Property AuthorizationCodeFailed() As String
            Get
                Return ResourceManager.GetString("AuthorizationCodeFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cancel!.
        '''</summary>
        Friend Shared ReadOnly Property Cancel() As String
            Get
                Return ResourceManager.GetString("Cancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Check run code ....
        '''</summary>
        Friend Shared ReadOnly Property CheckInBoot() As String
            Get
                Return ResourceManager.GetString("CheckInBoot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Check model ....
        '''</summary>
        Friend Shared ReadOnly Property CheckModel() As String
            Get
                Return ResourceManager.GetString("CheckModel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Please choose an area ....
        '''</summary>
        Friend Shared ReadOnly Property ChoiceArea() As String
            Get
                Return ResourceManager.GetString("ChoiceArea", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Failed to download the database, network congestion detected!.
        '''</summary>
        Friend Shared ReadOnly Property DatabaseFailed() As String
            Get
                Return ResourceManager.GetString("DatabaseFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Database update ....
        '''</summary>
        Friend Shared ReadOnly Property DatabaseUpdate() As String
            Get
                Return ResourceManager.GetString("DatabaseUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Device information update ....
        '''</summary>
        Friend Shared ReadOnly Property DeviceInfoUpdate() As String
            Get
                Return ResourceManager.GetString("DeviceInfoUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Device initialization ....
        '''</summary>
        Friend Shared ReadOnly Property DeviceInitialization() As String
            Get
                Return ResourceManager.GetString("DeviceInitialization", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Device reset ....
        '''</summary>
        Friend Shared ReadOnly Property DeviceReset() As String
            Get
                Return ResourceManager.GetString("DeviceReset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Device revise ....
        '''</summary>
        Friend Shared ReadOnly Property DeviceRevise() As String
            Get
                Return ResourceManager.GetString("DeviceRevise", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Device revise failure, please re-connect the USB and re-update!.
        '''</summary>
        Friend Shared ReadOnly Property DeviceReviseFailure() As String
            Get
                Return ResourceManager.GetString("DeviceReviseFailure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Device update ....
        '''</summary>
        Friend Shared ReadOnly Property DeviceUpdate() As String
            Get
                Return ResourceManager.GetString("DeviceUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a The device update has been successfully completed!.
        '''</summary>
        Friend Shared ReadOnly Property DeviceUpdateCompleted() As String
            Get
                Return ResourceManager.GetString("DeviceUpdateCompleted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Device has been reset, updated information unfinished!.
        '''</summary>
        Friend Shared ReadOnly Property DeviceUpdateUnfinished() As String
            Get
                Return ResourceManager.GetString("DeviceUpdateUnfinished", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Downloading.
        '''</summary>
        Friend Shared ReadOnly Property Downloading() As String
            Get
                Return ResourceManager.GetString("Downloading", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Download required software for updating ....
        '''</summary>
        Friend Shared ReadOnly Property DownloadSoftware() As String
            Get
                Return ResourceManager.GetString("DownloadSoftware", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Can not find device, please re-update!.
        '''</summary>
        Friend Shared ReadOnly Property FindDeviceFailed() As String
            Get
                Return ResourceManager.GetString("FindDeviceFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Download area accessed ....
        '''</summary>
        Friend Shared ReadOnly Property GetAreaAccess() As String
            Get
                Return ResourceManager.GetString("GetAreaAccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Obtain authorization code ....
        '''</summary>
        Friend Shared ReadOnly Property GetCode() As String
            Get
                Return ResourceManager.GetString("GetCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Device initialization failure, please re-update!.
        '''</summary>
        Friend Shared ReadOnly Property InitializationFailure() As String
            Get
                Return ResourceManager.GetString("InitializationFailure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a The database can be updated, the device will reset after five seconds ....
        '''</summary>
        Friend Shared ReadOnly Property IsNewVersion() As String
            Get
                Return ResourceManager.GetString("IsNewVersion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a This model is lock!.
        '''</summary>
        Friend Shared ReadOnly Property ModelIsLock() As String
            Get
                Return ResourceManager.GetString("ModelIsLock", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Network congestion, please wait ....
        '''</summary>
        Friend Shared ReadOnly Property NetworkCongestion() As String
            Get
                Return ResourceManager.GetString("NetworkCongestion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Network congestion has been detected, please connect again!.
        '''</summary>
        Friend Shared ReadOnly Property NetworkDetected() As String
            Get
                Return ResourceManager.GetString("NetworkDetected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Can not find device, make sure that the model is set to dn Mode!.
        '''</summary>
        Friend Shared ReadOnly Property NoFindDevice() As String
            Get
                Return ResourceManager.GetString("NoFindDevice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Operations begin ....
        '''</summary>
        Friend Shared ReadOnly Property OperationsBegin() As String
            Get
                Return ResourceManager.GetString("OperationsBegin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Reading device information ....
        '''</summary>
        Friend Shared ReadOnly Property ReadingInfo() As String
            Get
                Return ResourceManager.GetString("ReadingInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Failed to read device information, the device will reset after five seconds!.
        '''</summary>
        Friend Shared ReadOnly Property ReadingInfoFailed() As String
            Get
                Return ResourceManager.GetString("ReadingInfoFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Failed to reset device, please re-update!.
        '''</summary>
        Friend Shared ReadOnly Property ResetFailed() As String
            Get
                Return ResourceManager.GetString("ResetFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Failed to download the revise code, network congestion detected!.
        '''</summary>
        Friend Shared ReadOnly Property ReviseFailed() As String
            Get
                Return ResourceManager.GetString("ReviseFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Server.
        '''</summary>
        Friend Shared ReadOnly Property Server() As String
            Get
                Return ResourceManager.GetString("Server", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a No Data.(Size).
        '''</summary>
        Friend Shared ReadOnly Property SizeIsNull() As String
            Get
                Return ResourceManager.GetString("SizeIsNull", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Re-switch device failure, please re-connect the USB and re-update!.
        '''</summary>
        Friend Shared ReadOnly Property SwitchToAtmel() As String
            Get
                Return ResourceManager.GetString("SwitchToAtmel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Switch device failure, please re-connect the USB and re-update!.
        '''</summary>
        Friend Shared ReadOnly Property SwitchToBooreeFailure() As String
            Get
                Return ResourceManager.GetString("SwitchToBooreeFailure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a User authentication ....
        '''</summary>
        Friend Shared ReadOnly Property UserAuthentication() As String
            Get
                Return ResourceManager.GetString("UserAuthentication", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Failed to download the user database, network congestion detected!.
        '''</summary>
        Friend Shared ReadOnly Property UserDatabaseFailed() As String
            Get
                Return ResourceManager.GetString("UserDatabaseFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Failed to download voice, network congestion detected!.
        '''</summary>
        Friend Shared ReadOnly Property VoiceFailed() As String
            Get
                Return ResourceManager.GetString("VoiceFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Failed to download voice table, network congestion detected!.
        '''</summary>
        Friend Shared ReadOnly Property VoiceTableFailed() As String
            Get
                Return ResourceManager.GetString("VoiceTableFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Voice table update ....
        '''</summary>
        Friend Shared ReadOnly Property VoiceTableUpdate() As String
            Get
                Return ResourceManager.GetString("VoiceTableUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Voice update ....
        '''</summary>
        Friend Shared ReadOnly Property VoiceUpdate() As String
            Get
                Return ResourceManager.GetString("VoiceUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Welcome speech update ....
        '''</summary>
        Friend Shared ReadOnly Property WelcomeSpeechUpdate() As String
            Get
                Return ResourceManager.GetString("WelcomeSpeechUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Failed to download welcome speech voice, network congestion detected!.
        '''</summary>
        Friend Shared ReadOnly Property WelcomeSpeechVoiceFailed() As String
            Get
                Return ResourceManager.GetString("WelcomeSpeechVoiceFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Failed to write database, please re-update!.
        '''</summary>
        Friend Shared ReadOnly Property WriteDatabaseFailed() As String
            Get
                Return ResourceManager.GetString("WriteDatabaseFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Device Initialization failure, please re-update!(Write).
        '''</summary>
        Friend Shared ReadOnly Property WriteInitializationFailure() As String
            Get
                Return ResourceManager.GetString("WriteInitializationFailure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Failed to reset device, please re-update!(Write).
        '''</summary>
        Friend Shared ReadOnly Property WriteResetFailed() As String
            Get
                Return ResourceManager.GetString("WriteResetFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Failed to write voice, please re-update!.
        '''</summary>
        Friend Shared ReadOnly Property WriteVoiceFailed() As String
            Get
                Return ResourceManager.GetString("WriteVoiceFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Failed to write voice table, please re-update!.
        '''</summary>
        Friend Shared ReadOnly Property WriteVoiceTableFailed() As String
            Get
                Return ResourceManager.GetString("WriteVoiceTableFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Failed to write welcome speech voice, please re-update!.
        '''</summary>
        Friend Shared ReadOnly Property WriteWelcomeSpeechVoiceFailed() As String
            Get
                Return ResourceManager.GetString("WriteWelcomeSpeechVoiceFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Please select the correct model!.
        '''</summary>
        Friend Shared ReadOnly Property WrongModel() As String
            Get
                Return ResourceManager.GetString("WrongModel", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
